import { StyleSheet } from 'react-native';

export const dashboardStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 30,
    gap: 14,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  profileCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 38,
    height: 38,
    borderRadius: 20,
  },
  avatarText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 13,
    color: '#FFFFFF',
  },
  profileTextWrap: {
    flex: 1,
  },
  profileName: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#111827',
  },
  profileEmail: {
    marginTop: 1,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#6B7280',
  },
  logoutButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  welcomeCard: {
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  welcomeTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 21,
    color: '#FFFFFF',
  },
  welcomeSubtitle: {
    marginTop: 7,
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    lineHeight: 20,
    color: '#FFEAF4',
  },
  warningCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFEDD5',
  },
  warningText: {
    flex: 1,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#9A3412',
  },
  insightCard: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#F4EDFF',
    borderWidth: 1,
    borderColor: '#E9D5FF',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  insightIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  insightTextWrap: {
    flex: 1,
    gap: 2,
  },
  insightTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#6D28D9',
  },
  insightText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#4C1D95',
    lineHeight: 18,
  },
  metricsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  metricCardWrap: {
    width: '48.5%',
  },
  metricCard: {
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.7)',
  },
  metricTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  metricIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricGrowth: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
  },
  metricTitle: {
    marginTop: 14,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#4B5563',
  },
  metricValue: {
    marginTop: 4,
    fontFamily: 'Poppins_700Bold',
    fontSize: 19,
    color: '#111827',
  },
  chartCard: {
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 16,
  },
  chartTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 17,
    color: '#111827',
  },
  chartSubtitle: {
    marginTop: 2,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#6B7280',
  },
  chartsGrid: {
    gap: 12,
  },
  barsWrap: {
    marginTop: 14,
    height: 170,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  barGroup: {
    width: '12%',
    alignItems: 'center',
    gap: 6,
  },
  barTrack: {
    width: '100%',
    height: 140,
    justifyContent: 'flex-end',
    borderRadius: 10,
    backgroundColor: '#ECEFF4',
    overflow: 'hidden',
  },
  barTrackLight: {
    width: '100%',
    height: 140,
    justifyContent: 'flex-end',
    borderRadius: 10,
    backgroundColor: '#FFF2E8',
    overflow: 'hidden',
  },
  barFill: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  barDay: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#6B7280',
  },
  recentCard: {
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  recentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewAllText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#7A30FF',
  },
  recentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: '#F8FAFC',
  },
  recentBadge: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1B92F1',
  },
  recentMain: {
    flex: 1,
  },
  recentTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#111827',
  },
  recentMeta: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#6B7280',
  },
  recentStats: {
    alignItems: 'flex-end',
    gap: 2,
  },
  recentStatText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#4B5563',
  },
  recentStatCalories: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#EA580C',
  },
  emptyText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#6B7280',
  },
});
