
import { StyleSheet } from 'react-native';

export const accueilStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F4F2F7',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 28,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  logoIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 17,
    color: '#E6468F',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  ctaBannerWrap: {
    marginTop: 6,
  },
  ctaBanner: {
    borderRadius: 22,
    paddingHorizontal: 20,
    paddingVertical: 22,
    alignItems: 'center',
    shadowColor: '#1A2032',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  ctaBannerTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    lineHeight: 26,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  ctaBannerSubtitle: {
    marginTop: 8,
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#F7EFFF',
    textAlign: 'center',
  },
  ctaBannerButton: {
    marginTop: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ctaBannerButtonText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 13,
    color: '#7A30FF',
  },
  featuresSection: {
    marginTop: 26,
  },
  featuresTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 19,
    lineHeight: 30,
    color: '#0B1531',
    textAlign: 'center',
  },
  featuresSubtitle: {
    marginTop: 8,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#415674',
    textAlign: 'center',
  },
  featuresImageWrap: {
    marginTop: 16,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    shadowColor: '#1A2032',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 5,
  },
  featuresImage: {
    width: '100%',
    height: 190,
    resizeMode: 'cover',
  },
  featuresGrid: {
    marginTop: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  featureCard: {
    flexBasis: '48%',
    maxWidth: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 12,
    marginBottom: 16,
    shadowColor: '#1A2032',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  featureIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  featureTitle: {
    marginTop: 10,
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    lineHeight: 22,
    color: '#0B1531',
  },
  featureDescription: {
    marginTop: 6,
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#3F536F',
  },
  highlightsSection: {
    marginTop: 22,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingTop: 14,
    paddingBottom: 10,
    paddingHorizontal: 10,
  },
  highlightsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  highlightItem: {
    width: '24%',
    alignItems: 'center',
  },
  highlightValue: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: '#C653A3',
  },
  highlightLabel: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 10,
    lineHeight: 13,
    color: '#30435F',
    textAlign: 'center',
    marginTop: 4,
  },
  highlightsBottomLine: {
    height: 4,
    backgroundColor: '#F3EDFB',
    borderRadius: 999,
    marginTop: 16,
  },
  signIn: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#313C55',
  },
  getStartedButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  getStartedText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#FFFFFF',
  },
  badge: {
    marginTop: 20,
    alignSelf: 'flex-start',
    backgroundColor: '#EDE4FF',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  badgeText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#7A30FF',
  },
  heroRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  heroCopy: {
    flex: 1,
  },
  heroTextWrap: {
    marginTop: 12,
  },
  heroImageWrap: {
    width: 170,
    height: 230,
    borderRadius: 18,
    overflow: 'hidden',
    alignSelf: 'center',
    backgroundColor: '#E9E4F3',
    shadowColor: '#1A2032',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  heroImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  heroTitleDark: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 22,
    lineHeight: 34,
    color: '#0B1531',
  },
  heroTitleLineMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  heroTitlePurple: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 22,
    lineHeight: 34,
    color: '#7A30FF',
  },
  heroTitlePink: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 22,
    lineHeight: 34,
    color: '#D04D8B',
  },
  heroDescription: {
    marginTop: 12,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    lineHeight: 22,
    color: '#50607D',
  },
  heroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  heroMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: '#E4E8F1',
  },
  heroMetaText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#33445F',
  },
  ctaRow: {
    marginTop: 18,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 12,
  },
  primaryCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryCtaText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  secondaryCta: {
    borderWidth: 1,
    borderColor: '#D3D8E2',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  secondaryCtaText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#33445F',
  },
  statsCardBorder: {
    marginTop: 22,
    borderRadius: 20,
    padding: 8,
    position: 'relative',
  },
  statsCardInner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  statsCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  statsCardEyebrow: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#8A95AA',
    textTransform: 'uppercase',
  },
  statsCardTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    color: '#10203B',
    marginTop: 2,
  },
  statsCardBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FFF4D3',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  statsCardBadgeText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#A85A00',
  },
  metricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 5,
  },
  metricIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  blueBox: {
    backgroundColor: '#1B95EF',
  },
  orangeBox: {
    backgroundColor: '#FF5A1F',
  },
  purpleBox: {
    backgroundColor: '#B24CF0',
  },
  metricTextWrap: {
    flex: 1,
  },
  metricLabel: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#72809A',
  },
  metricValue: {
    marginTop: -2,
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: '#0A1831',
  },
  metricGrowth: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#22A249',
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  summaryChip: {
    flex: 1,
    backgroundColor: '#F5F7FB',
    borderRadius: 14,
    paddingVertical: 10,
    alignItems: 'center',
  },
  summaryValue: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: '#12213C',
  },
  summaryLabel: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#75829B',
    marginTop: 2,
  },
  testimonialsSection: {
    marginTop: 24,
    marginBottom: 12,
  },
  testimonialsTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 19,
    lineHeight: 30,
    color: '#0B1531',
    textAlign: 'center',
  },
  testimonialsSubtitle: {
    marginTop: 8,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#415674',
    textAlign: 'center',
  },
  testimonialsRow: {
    marginTop: 20,
    paddingRight: 12,
    gap: 16,
  },
  testimonialCard: {
    width: 270,
    backgroundColor: '#F9F4FF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EDE2FF',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  testimonialQuote: {
    marginTop: 10,
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    lineHeight: 21,
    color: '#22395A',
  },
  authorRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  authorEmoji: {
    fontSize: 20,
  },
  authorName: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: '#0B1531',
  },
  authorRole: {
    marginTop: 2,
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#4B6280',
  },
});

