import { StyleSheet } from 'react-native';

export const activitiesStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 30,
    gap: 14,
  },
  overviewCard: {
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 16,
  },
  overviewTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 22,
    color: '#FFFFFF',
  },
  overviewStatsRow: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  overviewStatItem: {
    width: '48.5%',
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  overviewStatLabel: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#F3F4F6',
  },
  overviewStatValue: {
    marginTop: 4,
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    color: '#FFFFFF',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    minHeight: 54,
  },
  searchInput: {
    flex: 1,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    color: '#374151',
    paddingVertical: 12,
  },
  weeklyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  weeklyTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 19,
    color: '#0F172A',
  },
  weeklyRange: {
    marginTop: -4,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#64748B',
  },
  weeklyGoalsRow: {
    marginTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  weeklyGoalItem: {
    width: '31%',
    alignItems: 'center',
    gap: 6,
  },
  ringOuter: {
    width: 98,
    height: 98,
    borderRadius: 49,
    borderWidth: 10,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  ringArc: {
    position: 'absolute',
    width: 98,
    height: 98,
    borderRadius: 49,
    borderWidth: 10,
    borderColor: '#2F6BDE',
    borderLeftColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  ringInner: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringPercent: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: '#0F172A',
  },
  ringRatio: {
    marginTop: -2,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#475569',
  },
  weeklyMetricLabel: {
    textAlign: 'center',
    fontFamily: 'Poppins_700Bold',
    fontSize: 11,
    color: '#0F172A',
  },
  weeklyMetricValue: {
    textAlign: 'center',
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#475569',
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: '#111827',
  },
  label: {
    marginTop: 10,
    marginBottom: 6,
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#374151',
  },
  typesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  typeChip: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
  },
  typeChipActive: {
    borderColor: '#7A30FF',
    backgroundColor: '#F3E9FF',
  },
  typeText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#4B5563',
  },
  typeTextActive: {
    color: '#7A30FF',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#111827',
    backgroundColor: '#F9FAFB',
  },
  notesInput: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  goalToggleRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  labelInline: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#374151',
  },
  toggleButton: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F9FAFB',
  },
  toggleButtonActive: {
    borderColor: '#7A30FF',
    backgroundColor: '#F3E9FF',
  },
  toggleText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 11,
    color: '#6B7280',
  },
  toggleTextActive: {
    color: '#7A30FF',
  },
  submitButton: {
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: '#7A30FF',
    alignItems: 'center',
    paddingVertical: 11,
  },
  submitText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#FFFFFF',
  },
  listCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 8,
  },
  errorText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#B91C1C',
  },
  emptyText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#6B7280',
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#F1F5F9',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#F8FAFC',
  },
  activityMain: {
    flex: 1,
    gap: 2,
  },
  activityType: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#111827',
  },
  activityMeta: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#6B7280',
  },
  activityNotes: {
    marginTop: 2,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#334155',
  },
  deleteButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
  },
});

