import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F5F6FA',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 30,
    gap: 16,
  },
  backToDashboardButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EFF6FF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  backToDashboardText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 11,
    color: '#1D4ED8',
  },
  heroCard: {
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
    shadowColor: '#8A2BE2',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  heroLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  avatarWrap: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 59,
  },
  avatarText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 26,
    color: '#FFFFFF',
  },
  cameraBadge: {
    position: 'absolute',
    right: 2,
    bottom: 2,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E9D5FF',
  },
  heroTextWrap: {
    flex: 1,
  },
  heroName: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 19,
    color: '#FFFFFF',
  },
  heroEmail: {
    marginTop: -3,
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#FFE7FE',
  },
  badgesRow: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroBadge: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minWidth: 92,
  },
  badgeLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 11,
    color: '#FDF2FF',
  },
  badgeValue: {
    marginTop: -1,
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#FFFFFF',
  },
  editProfileButton: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  editProfileText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 13,
    color: '#8A2BE2',
  },
  errorCard: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  errorText: {
    flex: 1,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#92400E',
  },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statCard: {
    width: '48.2%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 12,
    gap: 5,
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  statIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  blueIconWrap: {
    backgroundColor: '#E0F2FE',
  },
  greenIconWrap: {
    backgroundColor: '#DCFCE7',
  },
  orangeIconWrap: {
    backgroundColor: '#FFEDD5',
  },
  purpleIconWrap: {
    backgroundColor: '#F5D0FE',
  },
  statValue: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    lineHeight: 22,
    color: '#0F172A',
  },
  statLabel: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    lineHeight: 18,
    color: '#475569',
  },
  formCard: {
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 10,
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    lineHeight: 30,
    color: '#0F172A',
    marginBottom: 8,
  },
  label: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 13,
    lineHeight: 21,
    color: '#334155',
    marginTop: 6,
  },
  inputWithIcon: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  disabledInputWrap: {
    backgroundColor: '#F1F5F9',
  },
  input: {
    flex: 1,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    lineHeight: 22,
    color: '#334155',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  disabledInput: {
    color: '#64748B',
  },
  rowInputs: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  thirdInputWrap: {
    flex: 1,
  },
  saveButton: {
    marginTop: 14,
    borderRadius: 14,
    backgroundColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  saveButtonDisabled: {
    opacity: 0.65,
  },
  saveButtonText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  healthCard: {
    borderRadius: 20,
    backgroundColor: '#E8F4FF',
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: '#D5E9FF',
  },
  healthRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  healthLabel: {
    flex: 1,
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    lineHeight: 20,
    color: '#475569',
  },
  healthValue: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    lineHeight: 22,
    color: '#0F172A',
    textAlign: 'right',
  },
  healthValueGreen: {
    color: '#16A34A',
  },
  currentShapeCard: {
    marginBottom: 6,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DBEAFE',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  currentShapeTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  currentShapeTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#1E3A8A',
  },
  currentShapeScore: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 13,
    color: '#1D4ED8',
  },
  currentShapeTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#DBEAFE',
    overflow: 'hidden',
  },
  currentShapeFill: {
    height: '100%',
    backgroundColor: '#2563EB',
  },
  currentShapeHint: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#1E40AF',
  },
  timelineCard: {
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 10,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  timelineDot: {
    marginTop: 5,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#16A34A',
  },
  timelineDotBlue: {
    backgroundColor: '#2563EB',
  },
  timelineDotOrange: {
    backgroundColor: '#F97316',
  },
  timelineTextWrap: {
    flex: 1,
  },
  timelineTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#0F172A',
  },
  timelineMeta: {
    marginTop: 1,
    fontFamily: 'Poppins_400Regular',
    fontSize: 11,
    color: '#64748B',
  },
});

